#!/bin/bash 
git add . # tiek pieteiktas adreses "uzmanīšanai"
git config --global user.name osskario
git config --global user.email oskarsnaudins@gmail.com
#git commit -m "Class_04"
git commit -m "Class_$1"
git push origin main

